variables:
  - name: Build.Repository.Clean
    value: true
  - name: _DotNetCliPackageType
    value: sdk
  - name: _DotNetCliVersion
    value: 2.1.403

# CI and PR triggers
pr:
- master

jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: Windows_NT
    enablePublishBuildArtifacts: true
    pool:
      name: dotnet-internal-temp
      queue: Windows.10.Amd64.Open
    steps:
    - script: eng\common\cibuild.cmd
        -configuration Release
        -prepareMachine
        -projects $(Build.SourcesDirectory)/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
        -- /p:targetgroup=netstandard2.0 /p:targetswindows=true /p:targetframework=netstandard2.0
      name: Build
      displayName: Build
      condition: succeeded()
    - task: PublishBuildArtifacts@1
      displayName: Publish Logs to VSTS
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_BuildConfig)'
        PublishLocation: Container
        ArtifactName: $(Agent.Os)_$(Agent.JobName)
      continueOnError: true
      condition: always()
