parameters:
  # This section is required because agent pool can't 
  # be read from a user-defined variable (Azure DevOps limitation)
  agentPool: dotnet-external-temp-vs2019
  runAsPublic: true
  repoName: dotnet/wcf

jobs:
- template: /eng/common/templates/jobs/jobs.yml
  parameters:
    runAsPublic: ${{ parameters.runAsPublic }}
    enableMicrobuild: false
    enablePublishBuildArtifacts: true
    enablePublishTestResults: true
    enablePublishBuildAssets: false
    enableTelemetry: true
    helixRepo: $(repoName)

    jobs:
    - job: Windows_NT
      pool: ${{ parameters.agentPool }}

      variables:

        # needed for signing
        - name: _TeamName
          value: DotNetCore
        - name: _SignType
          value: test
        - name: _SignArgs
          value: ''
        - name: _Sign
          value: true

        # needed for darc (dependency flow) publishing
        - name: _PublishType
          value: none
        - name: _DotNetPublishToBlobFeed
          value: false
        - name: _PublishArgs
          value: ''
        - name: _OfficialBuildIdArgs
          value: ''

        # needed for helix jobs
        - name: _UnitTestHelixAgentPool
          value: 'Windows.10.Amd64.Open'
        - name: _WcfTestBinDir
          value: $(BUILD.SOURCESDIRECTORY)\artifacts\bin\WcfTest\$(_BuildConfig)\netcoreapp3.0
        - name: _WcfFuncTestBinDir
          value: $(BUILD.SOURCESDIRECTORY)\artifacts\bin\Wcf.Func.Tests\$(_BuildConfig)\netcoreapp3.0
        - name: _HelixStagingDir
          value: $(BUILD.STAGINGDIRECTORY)\helix\functests
        - name: _HelixSource
          value: ${{ parameters.repoName }}/$(Build.SourceBranch)
        - name: _HelixToken
          value: ''
        - name: _HelixCreator
          value: ${{ parameters.repoName }}
        - name: _HelixType
          value: build/product
        - name: _HelixTestType
          value: test/product/
        - name: _XUnitTargetFramework
          value: netcoreapp2.0
        - name: _XUnitRunnerVersion
          value: 2.4.1
        - name: _DotNetCliPackageType
          value: sdk
        - name: _DotNetCliVersion
          value: 2.1.403
        - name: _HelixAccessToken
          value: ''

        # Override some values if we're building internally (not public)
        - ${{ if eq(parameters.runAsPublic, 'false') }}:

          # note: You have to use list syntax here (-name: value) or
          # you will get errors about declaring the same variable multiple times
          - name: _PublishType
            value: blob
          - name: _SignType
            value: real
          - name: _DotNetPublishToBlobFeed
            value: true
          - group: DotNet-Blob-Feed
          - group: DotNet-Symbol-Server-Pats
          # DotNet-HelixApi-Access provides: HelixApiAccessToken
          - group: DotNet-HelixApi-Access
          - name: _PublishBlobFeedUrl
            value: https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json

          # note: Even though they are referenced here, user defined variables (like $(_SignType))
          #are not resolved until the agent is running on the machine. They can be overridden any
          # time before they are resolved, like in the job matrix below (see Build_Debug)
          - name: _SignArgs
            value: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName) /p:Sign=$(_Sign)
          - name: _PublishArgs
            value: /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1)
              /p:DotNetPublishBlobFeedUrl=$(_PublishBlobFeedUrl)
              /p:DotNetPublishToBlobFeed=$(_DotNetPublishToBlobFeed)
              /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
              /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
          - name: _OfficialBuildIdArgs
            value: /p:OfficialBuildId=$(BUILD.BUILDNUMBER)

          - name: _HelixSource
            value: official/${{ parameters.repoName }}/$(Build.SourceBranch)
          - name: _HelixToken
            value: '$(HelixApiAccessToken)' # from DotNet-HelixApi-Access group
          - name: _HelixCreator
            value: '' #if _HelixToken is set, Creator must be empty

      strategy:
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            # override some variables for debug
            _PublishType: none
            _SignType: test
            _DotNetPublishToBlobFeed : false
          Build_Release:
            _BuildConfig: Release

      steps:
      - checkout: self
        clean: true

      # Build and rename binlog
      - script: eng\common\cibuild.cmd
          -prepareMachine
          -configuration $(_BuildConfig)
          $(_OfficialBuildIdArgs)
          /bl:$(BUILD.SOURCESDIRECTORY)\artifacts\log\$(_BuildConfig)\Build.binlog
        displayName: Build

      # Run unit tests and rename binlog
      - script: eng\common\cibuild.cmd
          -configuration $(_BuildConfig)
          $(_OfficialBuildIdArgs)
          -test
          /bl:$(BUILD.SOURCESDIRECTORY)\artifacts\log\$(_BuildConfig)\Test.binlog
        displayName: Run Unit Tests
        condition: succeeded()

      - template: /eng/common/templates/steps/send-to-helix.yml
        parameters:
          HelixSource: $(_HelixSource)
          HelixType: $(_HelixTestType)
          HelixTargetQueues: Windows.10.Amd64.Open;Windows.81.Amd64.Open;Windows.7.Amd64.Open
          XUnitProjects: '..\src\**\*.Tests.csproj'
          XUnitPublishTargetFramework: $(_XUnitTargetFramework)
          XUnitRuntimeTargetFramework: $(_XUnitTargetFramework)
          XUnitRunnerVersion: $(_XUnitRunnerVersion)
          IncludeDotNetCli: true
          DotNetCliPackageType: $(_DotNetCliPackageType)
          DotNetCliVersion: $(_DotNetCliVersion)
          EnableXUnitReporter: true
          WaitForWorkItemCompletion: true
          Creator: $(_HelixCreator)
          HelixAccessToken: $(_HelixAccessToken)
          condition: eq(variables['_BuildConfig'], 'Debug')
